/*  QUANDO IMPLEMENTAMOS UMA ARVORE BINARIA DE FORMA ESTATICA SEM USAR 'STRUCTS' NÓS DEVEMOS UTILIZAR UM VETOR DE INTEIROS
 *   PARA ARMAZENAR OS INDICES DOS VERTICE
 *   PARA ISSO DEVEMOS SEGUIR ALGUMAS REGRAS COMO:
 *  O INDICE '0' SEMPRE VAI SER O VERTICE PAI 
 *   PARA OS VERTICES FILHOS DEVEMOS USAR AS SEGUINTES FORMULAS 

 *  Fe = 2 * P + 1; ESSA É A FORMULA A SER USADA EM UM FILHO QUE VAI AO LADO ESQUERDO
 *  Fd = 2 * P + 2; ESSA É A FORMULA PARA UM FILHO A DIREITA
*/
#include <stdio.h>
#include <stdlib.h>
#include <strig.h>
