//PONTEIROS SERVEM PARA APONTAR PARA ENDEREÇOS FISICOS EM MEMORIA DAS VARIAVEIS
// PARA SE DECLARAR UM NOVO PONTEIRO USAMOS A DECLARAÇÃO DE VARIAVEIS COM UM * ANTES DO IDENTIFICADOR DA VARIAVEL
// FORA DA DECLARAÇÃO O * SERVE PARA NOS DAR ACESSO AO CONTEUDO DA VARIAVEL PARA QUAL ELE APONTA (RECUPERAR OU EDITAR O CONTEUDO)
#include <stdio.h>

int main(){
    int *p;
    int x = 12;
    int y = 0;
    
    p = &x; //NESSE CASO O PONTEIRO P RECEBE O ENDEREÇO FISICO DA VARIAVEL X, LOGO ELE PASSA A APONTAR PARA ESSA VARIAVEL EM QUESTÃO
    printf("%d\n", p);
    y = *p; //AQUI ESTAMOS RECUPERANDO O CONTEUDO DA VARIAVEL PARA QUAL P APONTA E PASSANDO PARA A VARIAVEL Y
    printf(p);
    printf("%d\n", y);

    //p = &x;
    printf("PonteiroX: %d\n", p); //CASO EU COLOQUE O %d EU VOU MOSTRAR NA TELA O CONTÉUDO DA VARIAVEL QUE O PONTEIRO APONTA
    printf("PonteiroX: %p\n", p); //SE EU COLOCAR O %p EU MOSTRO NA TELA ONDE O VARIAVEL ESTA ALOCADA EM MEMORIA FISICA 


}